<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2022-12-06T06:50:31+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'America/New_York',
];
