<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2022-12-06T06:50:31+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '9.1.3',
    'version_db_installed' => '20220908074900',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => 1670309431,
    ],
];
