<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2022-12-06T06:50:31+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Softmed Concrete CMS',
        ],
    ],
];
